#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0
#
# build-kernel.sh — deterministic single-translation-unit merge for the
# Curlee freestanding codegen.
#
# Why: `curlee build` (the freestanding codegen) crashes on programs with an
# `import` statement (std::filesystem error in the codegen import path — see
# docs/phase2-architecture.md §1/§8). The pure renderer modules stay separate
# for humans and VM tests; this script concatenates them (in dependency
# order) with kernel.curlee into a single self-contained .curlee file that
# the codegen accepts.
#
# Order matters (dependencies first): canvas.curlee -> glyphs.curlee ->
# assets.curlee -> json.curlee -> kernel.curlee. Each pure module contains NO
# `main`, so the merged file has exactly one `main` (from kernel.curlee). All
# modules are already individually verified by `make check`.
#
# When the Curlee codegen import fix lands, this script is deleted and
# kernel.curlee imports the modules natively.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$ROOT/build/kernel-merged.curlee}"

mkdir -p "$(dirname "$OUT")"

# The merged file: a single SPDX header + each module in dependency order.
# Modules are verified individually; kernel.curlee is the entry (has main).
MODULES=(
  "$ROOT/kernel/canvas.curlee"
  "$ROOT/kernel/glyphs.curlee"
  "$ROOT/kernel/assets.curlee"
  "$ROOT/kernel/json.curlee"
  "$ROOT/kernel/kernel.curlee"
)

# Guard: the freestanding codegen cannot handle `import` statements.
for f in "${MODULES[@]}"; do
  if grep -q '^import ' "$f"; then
    echo "build-kernel: error: $f contains an 'import' statement, which the" >&2
    echo "  freestanding codegen cannot process. Merge must be import-free." >&2
    exit 1
  fi
done

{
  echo "// SPDX-License-Identifier: GPL-3.0"
  echo "//"
  echo "// kernel-merged.curlee — SINGLE-TRANSLATION-UNIT kernel for the"
  echo "// freestanding codegen (generated by scripts/build-kernel.sh)."
  echo "//"
  echo "// This file is GENERATED — do not edit. Edit the modules in kernel/"
  echo "// and re-run the merge. When the Curlee codegen import bug is fixed,"
  echo "// this script is deleted and kernel.curlee imports the modules."
  echo "//"
  echo "// Modules (in dependency order): canvas, glyphs, assets, json, kernel."
  echo
  for f in "${MODULES[@]}"; do
    echo "// ==== $(basename "$f") ===="
    # Strip each module's own SPDX line (we emit one merged header above) and
    # append the body.
    grep -v '^// SPDX-License-Identifier:' "$f"
    echo
  done
} > "$OUT"

echo "build-kernel: wrote $OUT"
