#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0
#
# build-kernel.sh — deterministic single-translation-unit merge for the
# Curlee freestanding codegen.
#
# Why: `curlee build` (the freestanding codegen) crashes on programs with an
# `import` statement (std::filesystem error in the codegen import path — see
# docs/phase2-architecture.md §1/§8). The pure renderer modules stay separate
# for humans and VM tests; this script concatenates them (in dependency
# order) with kernel.curlee into a single self-contained .curlee file that
# the codegen accepts.
#
# Order matters (dependencies first): canvas.curlee -> glyphs.curlee ->
# assets.curlee -> fb.curlee -> json.curlee -> serial.curlee ->
# vga_setup.curlee -> vbe.curlee -> virtio_net.curlee -> e1000.curlee ->
# net_stack.curlee -> net_glue.curlee -> mb2.curlee -> kernel.curlee. Each
# pure module contains NO `main`, so the merged file has exactly one `main`
# (from kernel.curlee). All modules are already individually verified by
# `make check` (net_glue.curlee is verified via the merged file too — it
# calls net_stack.curlee's + (since gh issue #14) virtio_net.curlee's
# functions; fb.curlee is standalone-checkable because it inlines its ring/
# geometry constants rather than calling assets.curlee — the C-#define
# pattern it replaces).
#
# When the Curlee codegen import fix lands, this script is deleted and
# kernel.curlee imports the modules natively.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$ROOT/build/kernel-merged.curlee}"

mkdir -p "$(dirname "$OUT")"

# The merged file: a single SPDX header + each module in dependency order.
# Modules are verified individually; kernel.curlee is the entry (has main).
MODULES=(
  "$ROOT/kernel/canvas.curlee"
  "$ROOT/kernel/glyphs.curlee"
  "$ROOT/kernel/assets.curlee"
  "$ROOT/kernel/fb.curlee"
  "$ROOT/kernel/json.curlee"
  "$ROOT/kernel/serial.curlee"
  "$ROOT/kernel/vga_setup.curlee"
  "$ROOT/kernel/vbe.curlee"
  "$ROOT/kernel/virtio_net.curlee"
  "$ROOT/kernel/virtio_blk_helpers.curlee"
  "$ROOT/kernel/virtio_blk_layout.curlee"
  "$ROOT/kernel/virtio_blk_queue.curlee"
  "$ROOT/kernel/virtio_blk_requests.curlee"
  "$ROOT/kernel/virtio_blk_bounds.curlee"
  "$ROOT/kernel/virtio_blk_reqbuf.curlee"
  "$ROOT/kernel/virtio_blk_alloc.curlee"
  "$ROOT/kernel/virtio_blk_memory.curlee"
  "$ROOT/kernel/virtio_blk_transport.curlee"
  "$ROOT/kernel/virtio_blk_io.curlee"
  "$ROOT/kernel/e1000.curlee"
  "$ROOT/kernel/irq_snn_guard.curlee"
  "$ROOT/kernel/net_stack.curlee"
  "$ROOT/kernel/net_glue.curlee"
  "$ROOT/kernel/mb2.curlee"
  "$ROOT/kernel/kernel.curlee"
)

# Application slot: APP_MODULES (space-separated .curlee file paths, may
# be absolute and outside this tree) are appended after the kernel
# modules. Curlee has no weak symbols and `--define` only resolves
# constants inside expressions (no text substitution — see `curlee
# build --help`), so main()'s app_init/app_frame calls need a real
# definition every build; when APP_MODULES is empty this falls back to
# the in-tree no-op app so the build still links.
if [[ -n "${APP_MODULES:-}" ]]; then
  APP_FILES=(${APP_MODULES})
else
  APP_FILES=("$ROOT/apps/noop/app.curlee")
fi
for f in "${APP_FILES[@]}"; do
  if [[ ! -f "$f" ]]; then
    echo "build-kernel: error: APP_MODULES file not found: $f" >&2
    exit 1
  fi
done
MODULES+=("${APP_FILES[@]}")

# Guard: the freestanding codegen cannot handle `import` statements.
for f in "${MODULES[@]}"; do
  if grep -q '^import ' "$f"; then
    echo "build-kernel: error: $f contains an 'import' statement, which the" >&2
    echo "  freestanding codegen cannot process. Merge must be import-free." >&2
    exit 1
  fi
done

{
  echo "// SPDX-License-Identifier: GPL-3.0"
  echo "//"
  echo "// kernel-merged.curlee — SINGLE-TRANSLATION-UNIT kernel for the"
  echo "// freestanding codegen (generated by scripts/build-kernel.sh)."
  echo "//"
  echo "// This file is GENERATED — do not edit. Edit the modules in kernel/"
  echo "// and re-run the merge. When the Curlee codegen import bug is fixed,"
  echo "// this script is deleted and kernel.curlee imports the modules."
  echo "//"
  echo "// Modules (in dependency order): canvas, glyphs, assets, fb, json, serial, vga_setup, vbe, virtio_net, e1000, irq_snn_guard, net_stack, net_glue, mb2, kernel."
  echo
  for f in "${MODULES[@]}"; do
    echo "// ==== $(basename "$f") ===="
    # Strip each module's own SPDX line (we emit one merged header above) and
    # append the body.
    grep -v '^// SPDX-License-Identifier:' "$f"
    echo
  done
} > "$OUT"

echo "build-kernel: wrote $OUT"
