#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0
#
# run-net-stack-codegen.sh — Phase 2d-2 HOST-SIDE WIRE PROOF of the one-shot
# TCP/IP stack glue (gh issue #12).
#
# The qemu-llm-smoke gate (2d-4) exercises the real wire path but needs host
# port 8080 free for the deterministic stub — on dev hosts a foreign service
# often owns it, so the gate refuses to run (by design). This harness proves
# the SAME wire behavior with no NIC and no live gate, following the
# json-codegen-run precedent (scripts/run-json-codegen.sh): the freestanding
# CODEGEN path has no VM limits, so it can drive the ACTUAL glue functions
# (kernel/net_glue.curlee — net_connect/net_send/net_stack_poll/
# net_response_len/net_response_byte) on the host against a SCRIPTED NIC.
#
# How it works:
#   1. Builds a single-TU probe: kernel/net_stack.curlee (pure protocol core)
#      + kernel/net_glue.curlee (the one-shot glue + extern declarations) + a
#      main that drives the round-trip (connect -> send -> poll -> read body),
#      exactly like kernel.curlee's net_llm_roundtrip.
#   2. Codegens it with `curlee build --target freestanding-c`.
#   3. Compiles it with a host harness that:
#        - mocks the 2d-1 NIC externs (net_link_up/net_mac_byte/
#          net_tx_stage_byte/net_tx_send/net_rx_*/net_rx_wait/
#          net_arp_request_gateway) — the net_state_*/net_resp_* state
#          functions are GENUINE Curlee statics inside the probe TU (gh issue
#          #20; the kernel/net_stack.c raw-state shim is deleted, so nothing
#          C is linked for them),
#        - replays the scripted RX frames: an ARP reply, a SYN-ACK
#          (peer ISN 0x12345678), then the stub server's 126-byte response
#          SPLIT across two TCP segments (90 header bytes + 36 body bytes) so
#          the cross-poll streaming path (net_poll_state persistence) is
#          exercised, and
#        - records every staged TX frame.
#   4. Asserts byte-for-byte:
#        - the SYN frame (60 B): gw MAC dst, guest MAC src, ethertype 0x0800,
#          IP total 40, IP checksum 0x108C, TCP checksum 0xA841 (the C ground
#          truth), flags 0x02, pad 54..59,
#        - the ACK frame (60 B): seq 0x10000001, ack = peer ISN + 1, flags
#          0x10, checksum = the C RFC 1071 algorithm over the same bytes,
#        - the REQ frame (211 B): the exact 157-byte request payload
#          (121-byte header + 36-byte body) at offsets 54..210, IP total 197,
#          IP checksum 0x0FEF (ground truth), checksum = the C algorithm,
#        - the poll loop returns 1 with net_response_len()==36 and the body
#          equals {"tool":"frame_tick","args":[0,1,2]} (asserted inside the
#          probe's own main — the Curlee static store, gh issue #20).
#
# The VM suite (kernel/net_stack_test.curlee) proves the pure checksums equal
# the C ground truth for the pinned one-shot values; this harness proves the
# GLUE stages the exact C wire frames and streams the response body through
# the Curlee static state — identical wire behavior to the former net_stack.c.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="$ROOT/build"
CURLEE="${CURLEE:-$(bash "$ROOT/scripts/find-curlee.sh")}"

mkdir -p "$BUILD"

# 1. The probe TU: pure core + glue + round-trip drive.
PROBE="$BUILD/net_stack_codegen_probe.curlee"
{
  echo "// SPDX-License-Identifier: GPL-3.0"
  echo "// Generated by scripts/run-net-stack-codegen.sh — do not edit."
  echo "// Drives the one-shot TCP/IP glue against a scripted NIC."
  grep -v '^// SPDX-License-Identifier:' "$ROOT/kernel/net_stack.curlee"
  echo
  grep -v '^// SPDX-License-Identifier:' "$ROOT/kernel/net_glue.curlee"
  cat <<'EOF'

// The 2d-1 NIC driver surface. gh issue #14: kernel/net_glue.curlee no longer
// declares these (they are GENUINE Curlee functions in kernel/virtio_net.curlee
// in the kernel TU), so this probe re-declares them for the host harness to
// MOCK — this harness tests the GLUE, not the driver (the driver itself is
// verified by `make check` + the qemu-net-smoke live gate). The signatures
// mirror the real driver (pm: cap phys.mem first); the codegen drops pm, so
// the harness's plain C mocks (net_rx_byte(long long i) etc.) still match.
extern fn net_probe(pm: cap phys.mem) -> Int;
extern fn net_init(pm: cap phys.mem) -> Int;
extern fn net_link_up() -> Int;
extern fn net_rx_len(pm: cap phys.mem) -> Int;
extern fn net_rx_byte(pm: cap phys.mem, i: Int) -> Int;
extern fn net_rx_done(pm: cap phys.mem) -> Unit;
extern fn net_tx_stage_byte(pm: cap phys.mem, i: Int, b: Int) -> Int;
extern fn net_tx_send(pm: cap phys.mem, len: Int) -> Int;
extern fn net_mac_byte(i: Int) -> Int;
extern fn net_poll_tick(pm: cap phys.mem) -> Int;
extern fn net_rx_wait(pm: cap phys.mem) -> Int;
extern fn net_arp_request_gateway(pm: cap phys.mem) -> Int;

// The round-trip drive (mirrors kernel.curlee's net_llm_roundtrip + the 2d-3
// body read): connect to 8080, send the fixed 36-byte request, poll until the
// response body is ready, then read it back. Returns a UNIQUE non-zero code
// per failed step so the harness can pinpoint a break. `pm` is dropped by the
// codegen (the glue functions compile to plain C signatures — the harness's
// curlee_main() call is unchanged).
fn main(pm: cap phys.mem) -> Int {
  let c: Int = net_connect(pm, 8080);
  if (c != 1) { return 1; }
  let s: Int = net_send(pm, 36);
  if (s != 1) { return 2; }
  let p: Int = 0;
  let guard: Int = 0;
  while (guard < 64) {
    let r: Int = net_stack_poll(pm);
    if (r != 0) {
      p = r;
      guard = 64;
    } else {
      guard = guard + 1;
    }
  }
  if (p != 1) { return 3; }
  let len: Int = net_response_len();
  if (len != 36) { return 4; }
  let b0: Int = net_response_byte(0);
  if (b0 != 123) { return 5; }   // '{'
  let b35: Int = net_response_byte(35);
  if (b35 != 125) { return 6; }  // '}'
  let sum: Int = 0;
  let i: Int = 0;
  while (i < len) {
    let b: Int = net_response_byte(i);
    sum = sum + b;
    i = i + 1;
  }
  if (sum != 2951) { return 7; }  // the 36-byte envelope byte sum
  return 0;
}
EOF
} > "$PROBE"

# 2. Codegen to freestanding C.
"$CURLEE" build --target freestanding-c -o "$BUILD/net_stack_codegen_probe.c" "$PROBE"

# 3. The host harness: scripted NIC + wire-frame assertions.
HARNESS="$BUILD/net_stack_codegen_harness.c"
cat > "$HARNESS" <<'EOF'
/* SPDX-License-Identifier: GPL-3.0 */
/* Host harness for the Phase 2d-2 wire probe (scripts/run-net-stack-codegen.sh). */
#include <stdio.h>
#include <string.h>

/* ---- RFC 1071 ones-complement checksum (the C ground-truth algorithm) ---- */
static unsigned short csum16(const unsigned char* p, int len)
{
    unsigned int sum = 0;
    int i;
    for (i = 0; i + 1 < len; i += 2)
    {
        sum += (unsigned int)((p[i] << 8) | p[i + 1]);
        if (sum > 0xFFFFu) sum = (sum & 0xFFFFu) + (sum >> 16);
    }
    if (len & 1)
    {
        sum += (unsigned int)p[len - 1] << 8;
        if (sum > 0xFFFFu) sum = (sum & 0xFFFFu) + (sum >> 16);
    }
    while (sum >> 16) sum = (sum & 0xFFFFu) + (sum >> 16);
    return (unsigned short)~sum;
}

/* ---- fixed constants (LOCKED, docs/phase2d-wire.md §1/§3) ---- */
static const unsigned char GW_MAC[6] = { 0x52, 0x55, 0x0A, 0x00, 0x02, 0x02 };
static const unsigned char OUR_MAC[6] = { 0x02, 0x00, 0x00, 0x00, 0x00, 0x01 };
static const char REQ_HEADER[] =
    "POST /completion HTTP/1.1\r\n"
    "Host: 10.0.2.2:8080\r\n"
    "Content-Type: application/json\r\n"
    "Content-Length: 36\r\n"
    "Connection: close\r\n"
    "\r\n";   /* 121 bytes */
static const char REQ_BODY[] = "{\"tool\":\"frame_tick\",\"args\":[0,1,2]}";  /* 36 */
/* The stub server's exact 126-byte response (scripts/llm_stub_server.py). */
static const char RESP[] =
    "HTTP/1.1 200 OK\r\n"
    "Content-Type: application/json\r\n"
    "Content-Length: 36\r\n"
    "Connection: close\r\n"
    "\r\n"
    "{\"tool\":\"frame_tick\",\"args\":[0,1,2]}";   /* 17+32+20+19+2+36 = 126 */

/* ---- scripted TX: record every staged frame ---- */
static unsigned char tx_buf[512];
static unsigned char tx_frames[8][512];
static int tx_lens[8];
static int tx_count = 0;

long long net_link_up(void) { return 1; }
long long net_mac_byte(long long i)
{
    if (i < 0 || i >= 6) { return 0; }
    return (long long)OUR_MAC[(int)i];
}
long long net_tx_stage_byte(long long i, long long b)
{
    if (i < 0 || i >= 512) { return 0; }
    tx_buf[(int)i] = (unsigned char)b;
    return 1;
}
long long net_tx_send(long long len)
{
    int n = (int)len;
    int i;
    if (tx_count >= 8 || n < 0 || n > 512) { return 0; }
    for (i = 0; i < n; ++i) { tx_frames[tx_count][i] = tx_buf[i]; }
    tx_lens[tx_count] = n;
    tx_count++;
    return 1;
}
long long net_arp_request_gateway(void) { return 1; }
long long net_probe(void) { return 1; }
long long net_init(void) { return 1; }
long long net_poll_tick(void) { return 0; }

/* ---- scripted RX: ARP reply, SYN-ACK, response seg A, response seg B ---- */
static unsigned char rx_frames[8][2048];
static int rx_lens[8];
static int rx_count = 0;
static int rx_index = 0;
static int rx_current = -1;

long long net_rx_wait(void)
{
    if (rx_index < rx_count)
    {
        rx_current = rx_index;
        return rx_lens[rx_index];
    }
    return 0;
}
long long net_rx_len(void)
{
    if (rx_current < 0) { return 0; }
    return rx_lens[rx_current];
}
long long net_rx_byte(long long i)
{
    if (rx_current < 0 || i < 0 || i >= rx_lens[rx_current]) { return 0; }
    return rx_frames[rx_current][(int)i];
}
void net_rx_done(void)
{
    if (rx_current >= 0) { rx_index = rx_current + 1; rx_current = -1; }
}

/* Build an IPv4/TCP segment from the gateway to us: Ethernet II + IPv4 +
 * TCP(payload, seq, flags) with correct RFC 1071 checksums. */
static void build_tcp_seg(unsigned char* out, const unsigned char* payload,
                          int payload_len, unsigned int seq, int flags)
{
    unsigned char ph[12];
    unsigned char ck_in[2048];
    int i, total = 20 + 20 + payload_len;
    unsigned short ick, tck;
    for (i = 0; i < 6; ++i) { out[i] = OUR_MAC[i]; out[6 + i] = GW_MAC[i]; }
    out[12] = 0x08; out[13] = 0x00;              /* ethertype IPv4 */
    out[14] = 0x45; out[15] = 0;
    out[16] = (total >> 8) & 0xFF; out[17] = total & 0xFF;
    out[18] = 0; out[19] = 0;                    /* ident */
    out[20] = 0; out[21] = 0;                    /* flags/frag */
    out[22] = 64; out[23] = 6;                   /* TTL, proto TCP */
    out[24] = 0; out[25] = 0;                    /* IP ck below */
    out[26] = 10; out[27] = 0; out[28] = 2; out[29] = 2;    /* src 10.0.2.2 */
    out[30] = 10; out[31] = 0; out[32] = 2; out[33] = 15;   /* dst 10.0.2.15 */
    ick = csum16(out + 14, 20);
    out[24] = (ick >> 8) & 0xFF; out[25] = ick & 0xFF;
    out[34] = 0x1F; out[35] = 0x90;              /* src port 8080 */
    out[36] = 0xC0; out[37] = 0x00;              /* dst port 49152 */
    out[38] = (seq >> 24) & 0xFF; out[39] = (seq >> 16) & 0xFF;
    out[40] = (seq >> 8) & 0xFF; out[41] = seq & 0xFF;
    out[42] = 0x10; out[43] = 0x00; out[44] = 0x00; out[45] = 0x01;  /* ack */
    out[46] = 0x50;                              /* data offset 5 */
    out[47] = (unsigned char)flags;
    out[48] = 0xFF; out[49] = 0xFF;              /* window */
    out[50] = 0; out[51] = 0;                    /* TCP ck below */
    out[52] = 0; out[53] = 0;                    /* urgent */
    for (i = 0; i < payload_len; ++i) { out[54 + i] = payload[i]; }
    ph[0] = 10; ph[1] = 0; ph[2] = 2; ph[3] = 2; /* src IP (gw) */
    ph[4] = 10; ph[5] = 0; ph[6] = 2; ph[7] = 15;/* dst IP (us) */
    ph[8] = 0; ph[9] = 6;
    ph[10] = (20 + payload_len) >> 8; ph[11] = (20 + payload_len) & 0xFF;
    memcpy(ck_in, ph, 12);
    memcpy(ck_in + 12, out + 34, 20 + payload_len);
    tck = csum16(ck_in, 12 + 20 + payload_len);
    out[50] = (tck >> 8) & 0xFF; out[51] = tck & 0xFF;
}

/* The codegen exports main as curlee_main (non-static entry). */
long long curlee_main(void);
/* The net state functions (net_state_*, net_resp_*, net_poll_*) are GENUINE
 * Curlee statics inside the probe TU (gh issue #20) — the harness no longer
 * links the kernel/net_stack.c raw-state shim; the probe's own main asserts
 * the body readback (rc == 0 covers len/bytes/sum). */

static int failures = 0;
#define CHECK(cond, msg) do { if (!(cond)) { printf("NET-CODEGEN: FAIL %s\n", msg); failures++; } } while (0)

static void script_rx(void)
{
    unsigned char f[2048];
    int i;
    /* Frame 0: ARP reply (drained by net_connect; content is best-effort). */
    memset(f, 0, sizeof(f));
    for (i = 0; i < 6; ++i) { f[i] = OUR_MAC[i]; f[6 + i] = GW_MAC[i]; }
    f[12] = 0x08; f[13] = 0x06;              /* ethertype ARP */
    f[15] = 0x01; f[16] = 0x08; f[18] = 6; f[19] = 4;
    f[20] = 0x00; f[21] = 0x02;              /* op = reply */
    for (i = 0; i < 6; ++i) { f[22 + i] = GW_MAC[i]; }   /* sha */
    f[28] = 10; f[29] = 0; f[30] = 2; f[31] = 2;         /* spa */
    for (i = 0; i < 6; ++i) { f[32 + i] = OUR_MAC[i]; }  /* tha */
    f[38] = 10; f[39] = 0; f[40] = 2; f[41] = 15;        /* tpa */
    rx_lens[0] = 60;
    memcpy(rx_frames[0], f, 60);
    /* Frame 1: SYN-ACK (peer ISN 0x12345678, SYN|ACK, no payload, 60 B). */
    build_tcp_seg(f, NULL, 0, 0x12345678u, 0x12);
    for (i = 54; i < 60; ++i) { f[i] = 0; }  /* pad to the 60-byte minimum */
    rx_lens[1] = 60;
    memcpy(rx_frames[1], f, 60);
    /* Frame 2: response header segment (90 payload bytes, PSH|ACK). */
    build_tcp_seg(f, (const unsigned char*)RESP, 90, 0x12345679u, 0x18);
    rx_lens[2] = 14 + 20 + 20 + 90;
    memcpy(rx_frames[2], f, rx_lens[2]);
    /* Frame 3: response body segment (36 payload bytes, seq continues). */
    build_tcp_seg(f, (const unsigned char*)RESP + 90, 36,
                  0x12345679u + 90, 0x18);
    rx_lens[3] = 14 + 20 + 20 + 36;
    memcpy(rx_frames[3], f, rx_lens[3]);
    rx_count = 4;
}

static void assert_syn(void)
{
    const unsigned char* f = tx_frames[0];
    int i;
    CHECK(tx_count >= 1 && tx_lens[0] == 60, "SYN frame length 60");
    CHECK(memcmp(f, GW_MAC, 6) == 0, "SYN dst = slirp gateway MAC");
    CHECK(memcmp(f + 6, OUR_MAC, 6) == 0, "SYN src = guest MAC");
    CHECK(f[12] == 0x08 && f[13] == 0x00, "SYN ethertype 0x0800");
    CHECK(f[14] == 0x45, "SYN IP version/IHL 0x45");
    CHECK(f[16] == 0x00 && f[17] == 40, "SYN IP total 40");
    CHECK(f[24] == 0x10 && f[25] == 0x8C, "SYN IP checksum 0x108C (ground truth)");
    CHECK(f[34] == 0xC0 && f[35] == 0x00, "SYN src port 49152");
    CHECK(f[36] == 0x1F && f[37] == 0x90, "SYN dst port 8080");
    CHECK(f[38] == 0x10 && f[39] == 0x00 && f[40] == 0x00 && f[41] == 0x00,
          "SYN seq 0x10000000");
    CHECK(f[46] == 0x50 && f[47] == 0x02, "SYN data offset 5, flags SYN");
    CHECK(f[50] == 0xA8 && f[51] == 0x41, "SYN TCP checksum 0xA841 (ground truth)");
    for (i = 54; i < 60; ++i) { CHECK(f[i] == 0, "SYN pad byte"); }
}

static void assert_ack(void)
{
    const unsigned char* f = tx_frames[1];
    CHECK(tx_count >= 2 && tx_lens[1] == 60, "ACK frame length 60");
    CHECK(memcmp(f, GW_MAC, 6) == 0, "ACK dst = gateway MAC");
    CHECK(f[38] == 0x10 && f[39] == 0x00 && f[40] == 0x00 && f[41] == 0x01,
          "ACK seq 0x10000001");
    /* ack = peer ISN (0x12345678) + 1 = 0x12345679 */
    CHECK(f[42] == 0x12 && f[43] == 0x34 && f[44] == 0x56 && f[45] == 0x79,
          "ACK ack = peer ISN + 1 (0x12345679)");
    CHECK(f[46] == 0x50 && f[47] == 0x10, "ACK data offset 5, flags ACK");
    {
        /* RFC 793: pseudo-header FIRST, then the TCP header with the checksum
         * field ZEROED (the wire bytes 50..51 are filled, so zero a copy). */
        unsigned char ph[12];
        unsigned char ck_in[64];
        unsigned short exp;
        ph[0] = 10; ph[1] = 0; ph[2] = 2; ph[3] = 15;   /* src IP (us) */
        ph[4] = 10; ph[5] = 0; ph[6] = 2; ph[7] = 2;    /* dst IP (gw) */
        ph[8] = 0; ph[9] = 6;
        ph[10] = 0; ph[11] = 20;                        /* TCP len 20 */
        memcpy(ck_in, ph, 12);
        memcpy(ck_in + 12, f + 34, 20);
        ck_in[12 + 16] = 0; ck_in[12 + 17] = 0;
        exp = csum16(ck_in, 32);
        CHECK(f[50] == ((exp >> 8) & 0xFF) && f[51] == (exp & 0xFF),
              "ACK TCP checksum = RFC 1071 over pseudo-header + segment");
    }
}

static void assert_req(void)
{
    const unsigned char* f = tx_frames[2];
    unsigned char ph[12];
    unsigned char ck_in[2048];
    unsigned short exp;
    CHECK(tx_count >= 3 && tx_lens[2] == 211, "REQ frame length 211");
    CHECK(memcmp(f, GW_MAC, 6) == 0, "REQ dst = gateway MAC");
    CHECK(f[16] == 0x00 && f[17] == 197, "REQ IP total 197");
    CHECK(f[24] == 0x0F && f[25] == 0xEF, "REQ IP checksum 0x0FEF (ground truth)");
    CHECK(f[38] == 0x10 && f[39] == 0x00 && f[40] == 0x00 && f[41] == 0x01,
          "REQ seq 0x10000001");
    CHECK(f[42] == 0x12 && f[43] == 0x34 && f[44] == 0x56 && f[45] == 0x79,
          "REQ ack = peer ISN + 1");
    CHECK(f[46] == 0x50 && f[47] == 0x18, "REQ data offset 5, flags PSH|ACK");
    CHECK(memcmp(f + 54, REQ_HEADER, 121) == 0, "REQ payload = 121-byte HTTP header");
    CHECK(memcmp(f + 54 + 121, REQ_BODY, 36) == 0, "REQ payload = 36-byte JSON body");
    ph[0] = 10; ph[1] = 0; ph[2] = 2; ph[3] = 15;   /* src IP (us) */
    ph[4] = 10; ph[5] = 0; ph[6] = 2; ph[7] = 2;    /* dst IP (gw) */
    ph[8] = 0; ph[9] = 6;
    ph[10] = 177 >> 8; ph[11] = 177 & 0xFF;         /* TCP len 20+157 */
    memcpy(ck_in, ph, 12);
    /* Zero the wire checksum field (bytes 50..51 = ck_in[16..17]) — RFC 793. */
    memcpy(ck_in + 12, f + 34, 177);
    ck_in[12 + 16] = 0; ck_in[12 + 17] = 0;
    exp = csum16(ck_in, 12 + 177);
    CHECK(f[50] == ((exp >> 8) & 0xFF) && f[51] == (exp & 0xFF),
          "REQ TCP checksum = RFC 1071 over pseudo-header + segment");
}

int main(void)
{
    script_rx();
    long long rc = curlee_main();
    if (rc != 0) {
        printf("NET-CODEGEN: FAIL probe returned %lld (1=connect 2=send 3=poll 4=len 5/6=body byte 7=body sum)\n", rc);
        return 1;
    }
    if (tx_count < 3) {
        printf("NET-CODEGEN: FAIL only %d TX frames staged (expected 3: SYN, ACK, REQ)\n", tx_count);
        return 1;
    }
    assert_syn();
    assert_ack();
    assert_req();
    /* The response body readback is asserted INSIDE the codegen probe (its
     * main returns a distinct code per failure — 4 len, 5/6 body bytes, 7
     * sum), so rc == 0 already proves the 36-byte body landed in the Curlee
     * static store (gh issue #20 — no C shim to read from). */
    if (failures == 0) {
        printf("NET-CODEGEN: PASS SYN/ACK/REQ wire frames + 36-byte response body (identical to the C stack)\n");
        return 0;
    }
    return 1;
}
EOF

# 4. Compile: the codegen probe + the host harness (the net state is genuine
#    Curlee statics inside the probe TU — gh issue #20 — so no C shim links).
cc -ffreestanding -fno-builtin -nostdlib -std=c11 -c "$BUILD/net_stack_codegen_probe.c" -o "$BUILD/net_stack_codegen_probe.o"
cc -ffreestanding -fno-builtin -nostdlib -std=c11 -c "$HARNESS" -o "$BUILD/net_stack_codegen_harness.o"
cc "$BUILD/net_stack_codegen_probe.o" "$BUILD/net_stack_codegen_harness.o" -o "$BUILD/net_stack_codegen_run"

if "$BUILD/net_stack_codegen_run"; then
  echo "PASS: net_stack glue stages the exact C wire frames and streams the stub response on the host (no NIC needed)"
else
  echo "FAIL: net_stack wire harness did not pass" >&2
  exit 1
fi
