#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0
#
# run-mb2-codegen.sh — gh issue #15 HOST-SIDE PROOF of the Curlee multiboot2
# tag walk (kernel/mb2.curlee, ported from the deleted kernel/mb2.c).
#
# The GRUB boot gate (make qemu-fb-smoke / qemu-loop-smoke) proves the live
# path end-to-end, but needs QEMU + a GRUB ISO. This harness proves the SAME
# parser contract deterministically on the host, following the json-codegen-run
# and net-stack-codegen-run precedents (scripts/run-json-codegen.sh,
# scripts/run-net-stack-codegen.sh): the freestanding CODEGEN path has no VM
# limits, so it can drive the ACTUAL Curlee mb2_parse against scripted
# physical memory.
#
# How it works:
#   1. Builds a single-TU probe: kernel/mb2.curlee (the real parser) + a main
#      that just returns mb2_parse(pm) — so curlee_main() == the parser's
#      return value (1 = usable 32bpp framebuffer tag found and globals
#      filled; 0 = not), the exact acceptance-contract.
#   2. Codegens it with `curlee build --target freestanding-c`.
#   3. Compiles it with a host harness that MOCKS the three extern windows
#      (mb2_info_addr_get / mb2_state_set / phys_read_u8+u32) against a
#      1 MiB byte array standing in for physical memory:
#        - the harness writes a synthetic multiboot2 info structure into the
#          array at runtime addresses (little-endian, exactly as GRUB does),
#        - phys_read_u8/u32 read the array at the given address (raw
#          byte/word reads — the same shape as the kernel's volatile loads),
#        - mb2_state_set records the (addr, pitch, width, height) the parser
#          extracted,
#      then drives curlee_main() across 11 scenarios and asserts BOTH the
#      return value AND the recorded state against the C ground truth.
#
# Scenarios (each mirrors a C mb2_parse code path):
#   1. happy path: cmdline tag (skipped via the 8-byte alignment math) then
#      the framebuffer tag -> rc 1, state (0xFD000000, 2560, 640, 480).
#   2. info addr == 0 (PVH path) -> rc 0, no state.
#   3. info addr >= 4 GiB -> rc 0, no state.
#   4. total_size < 16 -> rc 0.
#   5. total_size > 0x10000 -> rc 0.
#   6. no framebuffer tag before total_size -> rc 0.
#   7. framebuffer tag with bpp == 24 -> rc 0.
#   8. framebuffer tag with fb_addr == 0 -> rc 0.
#   9. malformed tag with size == 0 -> rc 0.
#  10. odd-sized tag (size 20 -> advance 24, exercising (size+7) & ~7) then
#      the framebuffer tag -> rc 1, state set.
#  11. framebuffer tag whose HIGH dword is non-zero (fb_addr = 0x1_00000000):
#      rc 0 — the Curlee gate requires addr_hi == 0 && addr_lo != 0 (the C
#      original truncated the u64 to the u32 fb_addr global and would have
#      returned 1 with an unusable fb_addr = 0 for this tag; the port is
#      strictly saner, see kernel/mb2.curlee's port notes).
#
# The boot gates then prove the real shim (kernel/mb2_state.c) + boot.S's
# mb2_info_addr + the live GRUB tag produce the same result in the VM.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="$ROOT/build"
CURLEE="${CURLEE:-$(bash "$ROOT/scripts/find-curlee.sh")}"

mkdir -p "$BUILD"

# 1. The probe TU: the real parser + a main that returns its result.
PROBE="$BUILD/mb2_codegen_probe.curlee"
{
  echo "// SPDX-License-Identifier: GPL-3.0"
  echo "// Generated by scripts/run-mb2-codegen.sh — do not edit."
  echo "// Drives the Curlee multiboot2 tag walk against scripted memory."
  grep -v '^// SPDX-License-Identifier:' "$ROOT/kernel/mb2.curlee"
  cat <<'EOF'

// The drive: main IS the parser's return contract (1 = usable 32bpp
// framebuffer tag found and globals filled; 0 = not). The harness calls
// curlee_main() once per scenario after re-arming the scripted info
// structure + recorded state.
fn main(pm: cap phys.mem) -> Int {
  return mb2_parse(pm);
}
EOF
} > "$PROBE"

# 2. Codegen to freestanding C.
"$CURLEE" build --target freestanding-c -o "$BUILD/mb2_codegen_probe.c" "$PROBE"

# 3. The host harness: scripted physical memory + the parser's extern windows.
HARNESS="$BUILD/mb2_codegen_harness.c"
cat > "$HARNESS" <<'EOF'
/* SPDX-License-Identifier: GPL-3.0 */
/* Host harness for the gh issue #15 mb2 tag-walk probe
 * (scripts/run-mb2-codegen.sh). */
#include <stdint.h>
#include <stdio.h>
#include <string.h>

/* ---- scripted physical memory: 1 MiB byte array (address == index) ---- */
#define MEM_SIZE 0x100000
static unsigned char mem[MEM_SIZE];

static void put_u8(unsigned long addr, unsigned int v)
{
    mem[addr] = (unsigned char)v;
}
static void put_u32(unsigned long addr, unsigned long v)
{
    mem[addr] = (unsigned char)(v & 0xFF);
    mem[addr + 1] = (unsigned char)((v >> 8) & 0xFF);
    mem[addr + 2] = (unsigned char)((v >> 16) & 0xFF);
    mem[addr + 3] = (unsigned char)((v >> 24) & 0xFF);
}
static void put_u64(unsigned long addr, unsigned long v)
{
    put_u32(addr, v & 0xFFFFFFFFUL);
    put_u32(addr + 4, (v >> 32) & 0xFFFFFFFFUL);
}

/* ---- the parser's extern windows (mocked) ---- */
static long long current_addr = 0;
static int state_called = 0;
static unsigned int state_addr, state_pitch, state_width, state_height;

long long mb2_info_addr_get(void)
{
    return current_addr;
}

void mb2_state_set(unsigned int addr, unsigned int pitch, unsigned int width,
                   unsigned int height)
{
    state_called = 1;
    state_addr = addr;
    state_pitch = pitch;
    state_width = width;
    state_height = height;
}

uint8_t phys_read_u8(int64_t addr)
{
    if (addr < 0 || (unsigned long)addr >= MEM_SIZE) { return 0; }
    return mem[(unsigned long)addr];
}

uint32_t phys_read_u32(int64_t addr)
{
    if (addr < 0 || (unsigned long)addr + 3 >= MEM_SIZE) { return 0; }
    return (uint32_t)mem[(unsigned long)addr]
         | ((uint32_t)mem[(unsigned long)addr + 1] << 8)
         | ((uint32_t)mem[(unsigned long)addr + 2] << 16)
         | ((uint32_t)mem[(unsigned long)addr + 3] << 24);
}

/* The codegen exports main as curlee_main (non-static entry; pm dropped). */
long long curlee_main(void);

/* ---- scenario bookkeeping ---- */
static int failures = 0;
#define CHECK(cond, msg) do { if (!(cond)) { printf("MB2-CODEGEN: FAIL %s\n", msg); failures++; } } while (0)

/* Reset the scripted memory + recorded state for a fresh scenario. */
static void reset_mem(void)
{
    memset(mem, 0, sizeof(mem));
    state_called = 0;
    state_addr = state_pitch = state_width = state_height = 0;
}

/* A minimal cmdline tag (type 0, size 12, 4-byte payload). */
static void put_cmdline_tag(unsigned long p)
{
    put_u32(p, 0);          /* type 0 (cmdline) */
    put_u32(p + 4, 12);     /* size 12 */
    put_u8(p + 8, 0);       /* "boot" NUL-terminated payload */
    put_u8(p + 9, 0);
    put_u8(p + 10, 0);
    put_u8(p + 11, 0);
}

/* The framebuffer tag (type 8, size 32) with the given bpp / fb addr. */
static void put_fb_tag(unsigned long p, unsigned long fb_addr, unsigned int bpp)
{
    put_u32(p, 8);          /* type 8 (framebuffer) */
    put_u32(p + 4, 32);     /* size 32 */
    put_u64(p + 8, fb_addr);
    put_u32(p + 16, 2560);  /* pitch */
    put_u32(p + 20, 640);   /* width */
    put_u32(p + 24, 480);   /* height */
    put_u8(p + 28, bpp);    /* bpp */
    put_u8(p + 29, 1);      /* type 1 = RGB */
    put_u8(p + 30, 0);      /* reserved */
    put_u8(p + 31, 0);
}

/* Run one scenario: arm the info structure, drive the parser, assert. The
 * caller must have reset_mem()'d and written the tags FIRST. */
static void run_case(const char* name, long long addr, unsigned long total,
                     int expect_rc, int expect_state,
                     unsigned int e_addr, unsigned int e_pitch,
                     unsigned int e_width, unsigned int e_height)
{
    long long rc;
    if (addr > 0 && addr < (long long)MEM_SIZE)
    {
        put_u32((unsigned long)addr, total);
        put_u32((unsigned long)addr + 4, 0);   /* reserved */
    }
    current_addr = addr;
    rc = curlee_main();
    CHECK(rc == expect_rc, name);
    if (expect_state)
    {
        CHECK(state_called == 1, name);
        CHECK(state_addr == e_addr, name);
        CHECK(state_pitch == e_pitch, name);
        CHECK(state_width == e_width, name);
        CHECK(state_height == e_height, name);
    }
    else
    {
        CHECK(state_called == 0, name);
    }
    if (rc != expect_rc || (expect_state && !state_called))
    {
        printf("MB2-CODEGEN: case %s: rc=%lld (want %d) state_called=%d\n",
               name, rc, expect_rc, state_called);
    }
}

int main(void)
{
    /* 1. Happy path: cmdline tag at 8 (advance 16) then fb tag at 24.
     *    total = 8 + 16 + 32 = 56. */
    reset_mem();
    put_cmdline_tag(0x80008);
    put_fb_tag(0x80018, 0xFD000000UL, 32);
    run_case("happy", 0x80000, 56, 1, 1, 0xFD000000u, 2560, 640, 480);

    /* 2. info addr == 0 (the PVH path: no boot stub). */
    reset_mem();
    run_case("zero_addr", 0, 0, 0, 0, 0, 0, 0, 0);

    /* 3. info addr >= 4 GiB. */
    reset_mem();
    run_case("big_addr", 0x100000000LL, 0, 0, 0, 0, 0, 0, 0);

    /* 4. total_size < 16. */
    reset_mem();
    run_case("small_total", 0x80000, 8, 0, 0, 0, 0, 0, 0);

    /* 5. total_size > 0x10000. */
    reset_mem();
    run_case("big_total", 0x80000, 0x10001, 0, 0, 0, 0, 0, 0);

    /* 6. No framebuffer tag: one cmdline tag, total = 8 + 16 = 24. */
    reset_mem();
    put_cmdline_tag(0x80008);
    run_case("no_fb_tag", 0x80000, 24, 0, 0, 0, 0, 0, 0);

    /* 7. Framebuffer tag with bpp == 24 (not usable). */
    reset_mem();
    put_fb_tag(0x80008, 0xFD000000UL, 24);
    run_case("bpp_not_32", 0x80000, 40, 0, 0, 0, 0, 0, 0);

    /* 8. Framebuffer tag with fb_addr == 0 (not usable). */
    reset_mem();
    put_fb_tag(0x80008, 0, 32);
    run_case("fb_addr_zero", 0x80000, 40, 0, 0, 0, 0, 0, 0);

    /* 9. Malformed: first tag has size == 0 (break out, return 0). */
    reset_mem();
    put_u32(0x80008, 8);     /* type 8 */
    put_u32(0x8000C, 0);     /* size 0 -> malformed guard */
    run_case("malformed_size0", 0x80000, 40, 0, 0, 0, 0, 0, 0);

    /* 10. Odd tag alignment: a size-20 tag at 8 (advance 24) then the fb tag
     *     at 32. total = 8 + 24 + 32 = 64. Exercises (size + 7) & ~7. */
    reset_mem();
    put_u32(0x80008, 5);     /* type 5 (framebuffer request) */
    put_u32(0x8000C, 20);    /* size 20 -> aligned advance 24 */
    put_u32(0x80010, 640);
    put_u32(0x80014, 480);
    put_u32(0x80018, 32);
    put_fb_tag(0x80020, 0xFD000000UL, 32);
    run_case("odd_alignment", 0x80000, 64, 1, 1, 0xFD000000u, 2560, 640, 480);

    /* 11. Framebuffer tag with a NON-ZERO HIGH dword (fb_addr =
     * 0x1_00000000): the Curlee gate requires addr_hi == 0 && addr_lo != 0,
     * so this tag is REJECTED (rc 0, no state). The C original truncated
     * the u64 to the u32 fb_addr global and would have returned 1 with an
     * unusable fb_addr = 0 for this tag — the port is strictly saner
     * (kernel/mb2.curlee's port notes). */
    reset_mem();
    put_fb_tag(0x80008, 0x100000000ULL, 32);
    run_case("fb_addr_hi", 0x80000, 40, 0, 0, 0, 0, 0, 0);

    if (failures == 0)
    {
        printf("MB2-CODEGEN: PASS all 11 scenarios (return contract + extracted "
               "framebuffer state identical to kernel/mb2.c)\n");
        return 0;
    }
    printf("MB2-CODEGEN: FAIL %d scenario(s)\n", failures);
    return 1;
}
EOF

# 4. Compile: the codegen probe (freestanding) + the host harness, link host.
cc -ffreestanding -fno-builtin -nostdlib -std=c11 -c "$BUILD/mb2_codegen_probe.c" -o "$BUILD/mb2_codegen_probe.o"
cc -ffreestanding -fno-builtin -nostdlib -std=c11 -c "$HARNESS" -o "$BUILD/mb2_codegen_harness.o"
cc "$BUILD/mb2_codegen_probe.o" "$BUILD/mb2_codegen_harness.o" -o "$BUILD/mb2_codegen_run"

if "$BUILD/mb2_codegen_run"; then
  echo "PASS: Curlee mb2_parse walks the multiboot2 structure and extracts the framebuffer tag on the host (no QEMU needed)"
else
  echo "FAIL: mb2 tag-walk harness did not pass" >&2
  exit 1
fi
