#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0
#
# run-json-codegen.sh — Phase 2d-3 freestanding-visible proof of the full
# LOCKED 36-byte envelope (GitHub issue #7 acceptance criterion 1).
#
# The Curlee VM's bytecode emitter has a total-program-size limit (~22 function
# calls), so `curlee run kernel/json_test.curlee` cannot feed the full 36-byte
# envelope through the parser's json_step on the VM. But the freestanding
# CODEGEN path (curlee build -> freestanding C) has no such limit, and its
# output is ordinary host-runnable C. This harness:
#   1. builds a single-TU probe (json.curlee + a main that feeds the envelope
#      through json_feed/json_end and returns the parse result),
#   2. codegens it with `curlee build --target freestanding-c`,
#   3. compiles it on the HOST with a tiny main that supplies the 36-byte
#      envelope via the net_response_* externs,
#   4. runs it and asserts err==0, tool_len==10, arg_count==3, arg_value==2.
#
# This is the authoritative gate for the full envelope (the VM suite covers
# the phases the emitter can run). A CI/reviewer can run it with no VM size
# limit and no NIC.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="$ROOT/build"
CURLEE="${CURLEE:-$(bash "$ROOT/scripts/find-curlee.sh")}"

mkdir -p "$BUILD"

# 1. The probe TU: json.curlee (contract-less parser) + a main that feeds the
#    full 36-byte envelope through the extern byte source.
PROBE="$BUILD/json_codegen_probe.curlee"
{
  echo "// SPDX-License-Identifier: GPL-3.0"
  echo "// Generated by scripts/run-json-codegen.sh — do not edit."
  echo "// Feeds the LOCKED 36-byte envelope through json_step/json_end."
  grep -v '^// SPDX-License-Identifier:' "$ROOT/kernel/json.curlee"
  cat <<'EOF'

// The 2d-2 byte source (this harness provides a real body, unlike the PVH
// stubs which return 0 — see the report).
extern fn net_response_len() -> Int;
extern fn net_response_byte(i: Int) -> Int;

fn json_feed(i: Int, rlen: Int, st: Int) -> Int {
  if (i >= rlen) {
    return st;
  } else {
    let c: Int = net_response_byte(i);
    let ns: Int = json_step(c, st);
    return json_feed(i + 1, rlen, ns);
  }
}

fn main() -> Int {
  let rlen: Int = net_response_len();
  if (rlen > 64) {
    return 1;   // too long
  }
  let st0: Int = json_start();
  let st: Int = json_feed(0, rlen, st0);
  let err: Int = json_end(st);
  if (err != 0) {
    return 100 + err;
  }
  let tl: Int = json_tool_len(st);
  if (tl > 15) {
    return 200;
  }
  let ac: Int = json_arg_count(st);
  if (ac > 8) {
    return 300;
  }
  let av: Int = json_arg_value(st);
  // Encode (err=0, tool_len, arg_count, arg_value) so the host harness can
  // assert each payload's exact fields. All fields are bounded: err 0..9,
  // tool_len 0..15, arg_count 0..8, arg_value -2^31..2^31-1. Encoding:
  //   rc = tool_len*10000 + arg_count*100 + (arg_value clipped to 0..99)
  // The harness uses distinct payloads whose arg_value fits 0..99 (the wire
  // doc's locked envelope and the regression payloads below all do).
  if (av < 0 || av > 99) {
    return 400;
  }
  return tl * 10000 + ac * 100 + av;
}
EOF
} > "$PROBE"

# 2. Codegen to freestanding C.
"$CURLEE" build --target freestanding-c -o "$BUILD/json_codegen_probe.c" "$PROBE"

# 3. Host harness: the same externs backed by the 36-byte locked envelope.
HARNESS="$BUILD/json_codegen_harness.c"
cat > "$HARNESS" <<'EOF'
/* SPDX-License-Identifier: GPL-3.0 */
/* Host harness for the Phase 2d-3 codegen probe (scripts/run-json-codegen.sh). */
#include <stdio.h>
#include <string.h>

/* Payloads under test (all within the wire doc's shape/limits). */
static const char* PAYLOADS[3];
static int PAYLOAD_LEN[3];
static int PAYLOAD_IDX = 0;

/* The LOCKED 36-byte envelope (docs/phase2d-wire.md §3): {"tool":"frame_tick","args":[0,1,2]} */
static const char ENVELOPE[] = "{\"tool\":\"frame_tick\",\"args\":[0,1,2]}";
/* Positive multi-digit args: the stale-magnitude regression case. */
static const char MULTI[] = "{\"tool\":\"x\",\"args\":[12,34]}";
/* Mixed positive/negative with a leading 0: [0,-1,2]. */
static const char MIXED[] = "{\"tool\":\"x\",\"args\":[0,-1,2]}";

/* The externs the probe expects (2d-2 surface) — backed by the ACTIVE payload. */
long long net_response_len(void) { return PAYLOAD_LEN[PAYLOAD_IDX]; }
long long net_response_byte(long long i)
{
    if (i < 0 || i >= PAYLOAD_LEN[PAYLOAD_IDX]) { return 0; }
    return (long long)PAYLOADS[PAYLOAD_IDX][(int)i];
}

/* The codegen exports main as curlee_main (non-static entry). */
long long curlee_main(void);

int main(void)
{
    PAYLOADS[0] = ENVELOPE; PAYLOAD_LEN[0] = (int)strlen(ENVELOPE);   /* 36 */
    PAYLOADS[1] = MULTI;    PAYLOAD_LEN[1] = (int)strlen(MULTI);      /* 22 */
    PAYLOADS[2] = MIXED;    PAYLOAD_LEN[2] = (int)strlen(MIXED);      /* 23 */

    int failures = 0;

    /* rc = tool_len*10000 + arg_count*100 + arg_value (see the probe main). */
    PAYLOAD_IDX = 0;
    long long rc0 = curlee_main();
    if (rc0 != 10 * 10000 + 3 * 100 + 2) {
        printf("JSON-CODEGEN: FAIL envelope rc=%lld (expected %d)\n", rc0, 10*10000 + 3*100 + 2);
        failures = 1;
    }

    PAYLOAD_IDX = 1;
    long long rc1 = curlee_main();
    if (rc1 != 1 * 10000 + 2 * 100 + 34) {
        printf("JSON-CODEGEN: FAIL [12,34] rc=%lld (expected %d)\n", rc1, 1*10000 + 2*100 + 34);
        failures = 1;
    }

    PAYLOAD_IDX = 2;
    long long rc2 = curlee_main();
    if (rc2 != 1 * 10000 + 3 * 100 + 2) {
        printf("JSON-CODEGEN: FAIL [0,-1,2] rc=%lld (expected %d)\n", rc2, 1*10000 + 3*100 + 2);
        failures = 1;
    }

    if (failures == 0) {
        printf("JSON-CODEGEN: PASS envelope(tool=frame_tick args=[0,1,2]) [12,34] [0,-1,2]\n");
        return 0;
    }
    return 1;
}
EOF

cc -ffreestanding -fno-builtin -nostdlib -std=c11 -c "$BUILD/json_codegen_probe.c" -o "$BUILD/json_codegen_probe.o"
cc -ffreestanding -fno-builtin -nostdlib -std=c11 -c "$HARNESS" -o "$BUILD/json_codegen_harness.o"
cc "$BUILD/json_codegen_probe.o" "$BUILD/json_codegen_harness.o" -o "$BUILD/json_codegen_run"

if "$BUILD/json_codegen_run"; then
  echo "PASS: full 36-byte locked envelope parses (tool=frame_tick, args=[0,1,2]) on the freestanding codegen path"
else
  echo "FAIL: full envelope parse did not produce the expected fields" >&2
  exit 1
fi
