#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0
#
# Exhaustive differential gate for the bounded CURLEE #316 logic unit.
# Compares generated Curlee C with nir-c-runtime for all 8,192 transitions,
# then compares the complete 4x4 controller state/event table.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="$ROOT/build"
CURLEE="${CURLEE:-$(bash "$ROOT/scripts/find-curlee.sh")}"
NIR_C_RUNTIME_ROOT="${NIR_C_RUNTIME_ROOT:-$ROOT/../nir-c-runtime}"

NIR_HEADER="$NIR_C_RUNTIME_ROOT/include/nir_c_runtime/fixed_event.h"
NIR_SOURCE="$NIR_C_RUNTIME_ROOT/src/fixed_event.c"
if [[ ! -f "$NIR_HEADER" || ! -f "$NIR_SOURCE" ]]; then
  echo "FAIL: nir-c-runtime fixed_event sources not found under $NIR_C_RUNTIME_ROOT" >&2
  exit 1
fi

mkdir -p "$BUILD"
PROBE="$BUILD/irq_snn_codegen_probe.curlee"
{
  echo "// Generated by scripts/run-irq-snn-codegen.sh — do not edit."
  grep -v '^// SPDX-License-Identifier:' "$ROOT/kernel/irq_snn_guard.curlee"
  echo 'fn main() -> Int { return 0; }'
} > "$PROBE"

"$CURLEE" build --target freestanding-c \
  -o "$BUILD/irq_snn_codegen_probe.c" "$PROBE"

HARNESS="$BUILD/irq_snn_codegen_harness.c"
cat > "$HARNESS" <<'EOF'
/* Generated host-only differential harness. */
#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>

#include "nir_c_runtime/fixed_event.h"
#include "irq_snn_codegen_probe.c"

static const nir_fixed_event_config_t LOGIC_CONFIG = {
    .weights = {2, 5, 1, 7},
    .bias = -4,
    .leak_shift = 2,
    .membrane_min = 0,
    .membrane_max = 31,
    .elevated_threshold = 16,
    .critical_threshold = 31,
};

int main(void) {
    /* Keep the wider provisional profile covered by the generated-C build;
       its exact sample values are asserted by the VM and C unit tests. */
    if (curlee_irq_snn_step(0, 10, 0, 5, 0) != 0 ||
        curlee_irq_snn_event(2882) != NIR_FIXED_EVENT_CRITICAL) {
        fputs("FAIL: wider fixed-event profile smoke mismatch\n", stderr);
        return 1;
    }
    uint64_t rows = 0;
    for (int32_t membrane = 0; membrane < 32; ++membrane) {
        for (uint8_t irq = 0; irq < 4; ++irq) {
            for (uint8_t timeout = 0; timeout < 4; ++timeout) {
                for (uint8_t pressure = 0; pressure < 4; ++pressure) {
                    for (uint8_t errors = 0; errors < 4; ++errors) {
                        const uint8_t features[4] = {irq, timeout, pressure, errors};
                        nir_fixed_event_state_t state = {.membrane = membrane};
                        uint8_t event = nir_fixed_event_step(&LOGIC_CONFIG, &state, features);
                        int64_t score = curlee_irq_snn_logic_step(
                            membrane, irq, timeout, pressure, errors);
                        int curlee_spike = curlee_irq_snn_logic_spike(score);
                        int c_spike = event != NIR_FIXED_EVENT_NORMAL;
                        if (score != state.membrane || curlee_spike != c_spike) {
                            fprintf(stderr,
                                    "FAIL row m=%" PRId32 " irq=%u timeout=%u pressure=%u errors=%u "
                                    "Curlee=(%" PRId64 ",%d) C=(%" PRId32 ",%d)\n",
                                    membrane, irq, timeout, pressure, errors,
                                    score, curlee_spike, state.membrane, c_spike);
                            return 1;
                        }
                        ++rows;
                    }
                }
            }
        }
    }

    for (uint8_t state = 0; state < 4; ++state) {
        for (uint8_t event = 0; event < 4; ++event) {
            int64_t curlee_next = curlee_irq_guard_next(state, event);
            int64_t curlee_action = curlee_irq_guard_action(state, event);
            uint8_t c_next = nir_fixed_guard_next(state, event);
            uint8_t c_action = nir_fixed_guard_action(state, event);
            if (curlee_next != c_next || curlee_action != c_action) {
                fprintf(stderr,
                        "FAIL controller state=%u event=%u Curlee=(%" PRId64 ",%" PRId64
                        ") C=(%u,%u)\n",
                        state, event, curlee_next, curlee_action, c_next, c_action);
                return 1;
            }
        }
    }

    printf("IRQ-SNN-CODEGEN: PASS all %" PRIu64
           " logic transitions + 16 controller transitions\n", rows);
    return 0;
}
EOF

cc -std=c11 -Wall -Wextra -Werror \
  -I"$BUILD" -I"$NIR_C_RUNTIME_ROOT/include" \
  "$HARNESS" "$NIR_SOURCE" -o "$BUILD/irq_snn_codegen_run"
"$BUILD/irq_snn_codegen_run"
