#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0
#
# run-mb2-codegen.sh — gh issue #15 HOST-SIDE PROOF of the Curlee multiboot2
# tag walk (kernel/mb2.curlee, ported from the deleted kernel/mb2.c).
#
# The GRUB boot gate (make qemu-fb-smoke / qemu-loop-smoke) proves the live
# path end-to-end, but needs QEMU + a GRUB ISO. This harness proves the SAME
# parser contract deterministically on the host, following the json-codegen-run
# and net-stack-codegen-run precedents (scripts/run-json-codegen.sh,
# scripts/run-net-stack-codegen.sh): the freestanding CODEGEN path has no VM
# limits, so it can drive the ACTUAL Curlee mb2_parse against scripted
# physical memory.
#
# How it works:
#   1. Builds a single-TU probe: kernel/mb2.curlee (the real parser) + a main
#      that just returns mb2_parse(pm) — so curlee_main() == the parser's
#      return value (1 = usable 32bpp framebuffer tag found and state filled;
#      0 = not), the exact acceptance-contract. mb2.curlee calls
#      kernel/fb.curlee's fb_state_set (gh issue #20 — the shared Curlee
#      framebuffer-state setter; the mb2_state_set C extern is gone), so the
#      probe prepends its extern declaration for the harness to mock.
#   2. Codegens it with `curlee build --target freestanding-c`.
#   3. Compiles it with a host harness that provides the extern windows
#      (mb2_info_addr — the extern static's codegen'd global — / fb_state_set)
#      and a 1 MiB byte array standing in for physical memory:
#        - phys_read_u8/u32 are now Curlee COMPILER BUILTINS (inline volatile
#          loads), so the harness writes the synthetic multiboot2 info
#          structure into the array at its REAL address (MEM_BASE + offset,
#          little-endian, exactly as GRUB does) and the parser's builtin
#          reads dereference it directly — the old extern mocks are dead
#          code kept for reference,
#        - fb_state_set records the (addr, pitch, width, height) the parser
#          extracted,
#      then drives curlee_main() across 12 scenarios and asserts BOTH the
#      return value AND the recorded state against the C ground truth.
#
# Scenarios (each mirrors a C mb2_parse code path):
#   1. happy path: cmdline tag (skipped via the 8-byte alignment math) then
#      the framebuffer tag -> rc 1, state (0xFD000000, 2560, 640, 480).
#   2. info addr == 0 (PVH path) -> rc 0, no state.
#   3. info addr >= 4 GiB -> rc 0, no state.
#   4. total_size < 16 -> rc 0.
#   5. total_size > 0x10000 -> rc 0.
#   6. no framebuffer tag before total_size -> rc 0.
#   7. framebuffer tag with bpp == 24 -> rc 0.
#   8. framebuffer tag with fb_addr == 0 -> rc 0.
#   9. malformed tag with size == 0 -> rc 0.
#  10. odd-sized tag (size 20 -> advance 24, exercising (size+7) & ~7) then
#      the framebuffer tag -> rc 1, state set.
#  11. framebuffer tag whose HIGH dword is non-zero (fb_addr = 0x1_00000000):
#      rc 0 — the Curlee gate requires addr_hi == 0 && addr_lo != 0 (the C
#      original truncated the u64 to the u32 fb_addr global and would have
#      returned 1 with an unusable fb_addr = 0 for this tag; the port is
#      strictly saner, see kernel/mb2.curlee's port notes).
#  12. info addr NEGATIVE (a u64 with bit 63 set — gh issue #31: the extern
#      static is a signed int64_t, so the value arrives negative): rc 0 — the
#      C original's UNSIGNED `>= 0x100000000ULL` rejects it, and the Curlee
#      gate must too (`base < 0`), BEFORE any physical read (a wild
#      dereference at (uintptr_t)-1 would now segfault the harness — the
#      builtin reads inline the deref, so a gate regression fails the run,
#      just less gracefully than the old mocks).
#
# The boot gates then prove the real path (kernel/mb2.curlee's extern static
# mb2_info_addr + boot.S's %ebx store into that codegen'd global + the live
# GRUB tag filling the Curlee framebuffer state via fb_state_set) produces
# the same result in the VM.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="$ROOT/build"
CURLEE="${CURLEE:-$(bash "$ROOT/scripts/find-curlee.sh")}"

mkdir -p "$BUILD"

# 1. The probe TU: the real parser + a main that returns its result.
PROBE="$BUILD/mb2_codegen_probe.curlee"
{
  echo "// SPDX-License-Identifier: GPL-3.0"
  echo "// Generated by scripts/run-mb2-codegen.sh — do not edit."
  echo "// Drives the Curlee multiboot2 tag walk against scripted memory."
  # gh issue #20: mb2.curlee calls kernel/fb.curlee's fb_state_set (a genuine
  # Curlee function in the kernel TU) without declaring it; this probe has no
  # fb.curlee, so the extern is declared here for the host harness to mock
  # (it records the extracted framebuffer state exactly like the deleted
  # mb2_state.c mb2_state_set did).
  cat <<'EOF'
extern fn fb_state_set(addr: Int, pitch: Int, width: Int, height: Int) -> Unit;
EOF
  grep -v '^// SPDX-License-Identifier:' "$ROOT/kernel/mb2.curlee"
  cat <<'EOF'

// The drive: main IS the parser's return contract (1 = usable 32bpp
// framebuffer tag found and globals filled; 0 = not). The harness calls
// curlee_main() once per scenario after re-arming the scripted info
// structure + recorded state.
fn main(pm: cap phys.mem) -> Int {
  return mb2_parse(pm);
}
EOF
} > "$PROBE"

# 2. Codegen to freestanding C.
"$CURLEE" build --target freestanding-c -o "$BUILD/mb2_codegen_probe.c" "$PROBE"

# 3. The host harness: scripted physical memory + the parser's extern windows.
HARNESS="$BUILD/mb2_codegen_harness.c"
cat > "$HARNESS" <<'EOF'
/* SPDX-License-Identifier: GPL-3.0 */
/* Host harness for the gh issue #15 mb2 tag-walk probe
 * (scripts/run-mb2-codegen.sh). */
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/mman.h>

/* ---- scripted physical memory: 1 MiB mapped at the classic x86 LOW-MEMORY
 * address 0x80000 (MAP_FIXED). The Curlee phys_read_u8/u32 calls are
 * COMPILER BUILTINS (inline volatile loads — the old extern mocks below are
 * dead code kept for reference), so the parser dereferences REAL addresses:
 * the parser's trust gate rejects an info base >= 4 GiB, and a static array
 * would sit at a userspace address far above that. Mapping at 0x80000 (a
 * well-known free low-memory hole) makes the base pass the gate AND the
 * builtin derefs hit real mapped memory. Scenario offsets are RELATIVE to
 * this base: physical address = MEM_BASE + offset. ---- */
#define MEM_SIZE 0x100000
#define MEM_BASE 0x80000
static unsigned char* mem;

static int mem_ready(void)
{
    if (mem)
    {
        return 1;
    }
    void* p = mmap((void*)MEM_BASE, MEM_SIZE,
                   PROT_READ | PROT_WRITE,
                   MAP_PRIVATE | MAP_ANONYMOUS | MAP_FIXED, -1, 0);
    if (p == MAP_FAILED)
    {
        fprintf(stderr, "MB2-CODEGEN: cannot map low memory at 0x80000\n");
        return 0;
    }
    mem = (unsigned char*)p;
    return 1;
}

static void put_u8(unsigned long addr, unsigned int v)
{
    mem[addr] = (unsigned char)v;
}
static void put_u32(unsigned long addr, unsigned long v)
{
    mem[addr] = (unsigned char)(v & 0xFF);
    mem[addr + 1] = (unsigned char)((v >> 8) & 0xFF);
    mem[addr + 2] = (unsigned char)((v >> 16) & 0xFF);
    mem[addr + 3] = (unsigned char)((v >> 24) & 0xFF);
}
static void put_u64(unsigned long addr, unsigned long v)
{
    put_u32(addr, v & 0xFFFFFFFFUL);
    put_u32(addr + 4, (v >> 32) & 0xFFFFFFFFUL);
}

/* ---- the parser's extern windows (mocked) ---- */
/* gh issue #31: mb2.curlee declares `extern static mb2_info_addr: Int = 0;`,
 * which the freestanding codegen emits as a plain global `int64_t
 * mb2_info_addr = 0;` (curlee #297 — external linkage, verbatim name). The
 * harness re-arms that global per scenario, exactly like boot.S's
 * `movl %ebx, mb2_info_addr` does on the GRUB path; the deleted
 * mb2_info_addr_get() C getter no longer exists to mock. */
extern long long mb2_info_addr;
static int state_called = 0;
static unsigned int state_addr, state_pitch, state_width, state_height;
static int failures = 0;

/* gh issue #20: mb2.curlee fills the framebuffer state through fb.curlee's
 * fb_state_set (a genuine Curlee function in the kernel TU; the deleted
 * mb2_state.c mb2_state_set extern). This mock records the extracted values
 * exactly like the old shim did — the probe's extern declaration matches the
 * Curlee signature, so the args arrive as int64_t. */
void fb_state_set(long long addr, long long pitch, long long width,
                  long long height)
{
    state_called = 1;
    state_addr = (unsigned int)addr;
    state_pitch = (unsigned int)pitch;
    state_width = (unsigned int)width;
    state_height = (unsigned int)height;
}

/* A NEGATIVE address is a WILD DEREFERENCE in the kernel ((uintptr_t)-1):
 * the mb2_parse trust gate (base < 0, matching the C original's unsigned
 * >= 0x100000000ULL) must reject it BEFORE any read. If a read still
 * arrives with addr < 0, that is a trust-gate regression — fail the run. */
static void wild_read_fail(int64_t addr)
{
    printf("MB2-CODEGEN: FAIL wild read at negative addr %lld "
           "(trust gate must reject before any read)\n", addr);
    failures++;
}

uint8_t phys_read_u8(int64_t addr)
{
    if (addr < 0) { wild_read_fail(addr); return 0; }
    if ((unsigned long)addr >= MEM_SIZE) { return 0; }
    return mem[(unsigned long)addr];
}

uint32_t phys_read_u32(int64_t addr)
{
    if (addr < 0) { wild_read_fail(addr); return 0; }
    if ((unsigned long)addr + 3 >= MEM_SIZE) { return 0; }
    return (uint32_t)mem[(unsigned long)addr]
         | ((uint32_t)mem[(unsigned long)addr + 1] << 8)
         | ((uint32_t)mem[(unsigned long)addr + 2] << 16)
         | ((uint32_t)mem[(unsigned long)addr + 3] << 24);
}

/* The codegen exports main as curlee_main (non-static entry; pm dropped). */
long long curlee_main(void);

/* ---- scenario bookkeeping ---- */
#define CHECK(cond, msg) do { if (!(cond)) { printf("MB2-CODEGEN: FAIL %s\n", msg); failures++; } } while (0)

/* Reset the scripted memory + recorded state for a fresh scenario. */
static void reset_mem(void)
{
    memset(mem, 0, MEM_SIZE);
    state_called = 0;
    state_addr = state_pitch = state_width = state_height = 0;
}

/* A minimal cmdline tag (type 0, size 12, 4-byte payload). */
static void put_cmdline_tag(unsigned long p)
{
    put_u32(p, 0);          /* type 0 (cmdline) */
    put_u32(p + 4, 12);     /* size 12 */
    put_u8(p + 8, 0);       /* "boot" NUL-terminated payload */
    put_u8(p + 9, 0);
    put_u8(p + 10, 0);
    put_u8(p + 11, 0);
}

/* The framebuffer tag (type 8, size 32) with the given bpp / fb addr. */
static void put_fb_tag(unsigned long p, unsigned long fb_addr, unsigned int bpp)
{
    put_u32(p, 8);          /* type 8 (framebuffer) */
    put_u32(p + 4, 32);     /* size 32 */
    put_u64(p + 8, fb_addr);
    put_u32(p + 16, 2560);  /* pitch */
    put_u32(p + 20, 640);   /* width */
    put_u32(p + 24, 480);   /* height */
    put_u8(p + 28, bpp);    /* bpp */
    put_u8(p + 29, 1);      /* type 1 = RGB */
    put_u8(p + 30, 0);      /* reserved */
    put_u8(p + 31, 0);
}

/* Run one scenario: arm the info structure, drive the parser, assert. The
 * caller must have reset_mem()'d and written the tags FIRST (at RELATIVE
 * offsets — physical address = MEM_BASE + offset). `base` is the raw
 * current_addr to arm (MEM_BASE for in-range scenarios; 0, a negative, or
 * >= 4 GiB for the trust-gate scenarios the parser must reject BEFORE any
 * physical read — with the builtin reads, a gate regression segfaults the
 * harness instead of the old mocks' graceful fail, still a clean gate fail).
 * `mem_off` is the offset to write `total` (the total_size field) at, or -1
 * to write nothing.
 */
static void run_case(const char* name, long long base, long long mem_off,
                     unsigned long total, int expect_rc, int expect_state,
                     unsigned int e_addr, unsigned int e_pitch,
                     unsigned int e_width, unsigned int e_height)
{
    long long rc;
    if (mem_off >= 0)
    {
        put_u32((unsigned long)mem_off, total);
        put_u32((unsigned long)mem_off + 4, 0);   /* reserved */
    }
    mb2_info_addr = base;
    rc = curlee_main();
    CHECK(rc == expect_rc, name);
    if (expect_state)
    {
        CHECK(state_called == 1, name);
        CHECK(state_addr == e_addr, name);
        CHECK(state_pitch == e_pitch, name);
        CHECK(state_width == e_width, name);
        CHECK(state_height == e_height, name);
    }
    else
    {
        CHECK(state_called == 0, name);
    }
    if (rc != expect_rc || (expect_state && !state_called))
    {
        printf("MB2-CODEGEN: case %s: rc=%lld (want %d) state_called=%d\n",
               name, rc, expect_rc, state_called);
    }
}

int main(void)
{
    if (!mem_ready())
    {
        return 1;
    }
    /* 1. Happy path: cmdline tag at offset 8 (advance 16) then fb tag at
     *    offset 24. total = 8 + 16 + 32 = 56. The info base is mem[0]
     *    (physical 0x80000). */
    reset_mem();
    put_cmdline_tag(0x8);
    put_fb_tag(0x18, 0xFD000000UL, 32);
    run_case("happy", MEM_BASE, 0, 56, 1, 1, 0xFD000000u, 2560, 640, 480);

    /* 2. info addr == 0 (the PVH path: no boot stub). */
    reset_mem();
    run_case("zero_addr", 0, -1, 0, 0, 0, 0, 0, 0, 0);

    /* 3. info addr >= 4 GiB. */
    reset_mem();
    run_case("big_addr", 0x100000000LL, -1, 0, 0, 0, 0, 0, 0, 0);

    /* 4. total_size < 16. */
    reset_mem();
    run_case("small_total", MEM_BASE, 0, 8, 0, 0, 0, 0, 0, 0);

    /* 5. total_size > 0x10000. */
    reset_mem();
    run_case("big_total", MEM_BASE, 0, 0x10001, 0, 0, 0, 0, 0, 0);

    /* 6. No framebuffer tag: one cmdline tag, total = 8 + 16 = 24. */
    reset_mem();
    put_cmdline_tag(0x8);
    run_case("no_fb_tag", MEM_BASE, 0, 24, 0, 0, 0, 0, 0, 0);

    /* 7. Framebuffer tag with bpp == 24 (not usable). */
    reset_mem();
    put_fb_tag(0x8, 0xFD000000UL, 24);
    run_case("bpp_not_32", MEM_BASE, 0, 40, 0, 0, 0, 0, 0, 0);

    /* 8. Framebuffer tag with fb_addr == 0 (not usable). */
    reset_mem();
    put_fb_tag(0x8, 0, 32);
    run_case("fb_addr_zero", MEM_BASE, 0, 40, 0, 0, 0, 0, 0, 0);

    /* 9. Malformed: first tag has size == 0 (break out, return 0). */
    reset_mem();
    put_u32(0x8, 8);     /* type 8 */
    put_u32(0xC, 0);     /* size 0 -> malformed guard */
    run_case("malformed_size0", MEM_BASE, 0, 40, 0, 0, 0, 0, 0, 0);

    /* 10. Odd tag alignment: a size-20 tag at 8 (advance 24) then the fb tag
     *     at 32. total = 8 + 24 + 32 = 64. Exercises (size + 7) & ~7. */
    reset_mem();
    put_u32(0x8, 5);     /* type 5 (framebuffer request) */
    put_u32(0xC, 20);    /* size 20 -> aligned advance 24 */
    put_u32(0x10, 640);
    put_u32(0x14, 480);
    put_u32(0x18, 32);
    put_fb_tag(0x20, 0xFD000000UL, 32);
    run_case("odd_alignment", MEM_BASE, 0, 64, 1, 1, 0xFD000000u, 2560, 640, 480);

    /* 11. Framebuffer tag with a NON-ZERO HIGH dword (fb_addr =
     * 0x1_00000000): the Curlee gate requires addr_hi == 0 && addr_lo != 0,
     * so this tag is REJECTED (rc 0, no state). The C original truncated
     * the u64 to the u32 fb_addr global and would have returned 1 with an
     * unusable fb_addr = 0 for this tag — the port is strictly saner
     * (kernel/mb2.curlee's port notes). */
    reset_mem();
    put_fb_tag(0x8, 0x100000000ULL, 32);
    run_case("fb_addr_hi", MEM_BASE, 0, 40, 0, 0, 0, 0, 0, 0);

    /* 12. Info addr NEGATIVE (a u64 with bit 63 set — e.g. a corrupted
     * global; gh issue #31 the extern static is a signed int64_t, so the
     * value arrives negative): the C original's UNSIGNED
     * `mb2_info_addr >= 0x100000000ULL` rejects it, and the Curlee gate must
     * too (base < 0), BEFORE any physical read. With the builtin reads a
     * gate regression would deref (uintptr_t)-1 and segfault — this case
     * proves the trust gate, not the mock. */
    reset_mem();
    run_case("negative_addr", -1LL, -1, 0, 0, 0, 0, 0, 0, 0);

    if (failures == 0)
    {
        printf("MB2-CODEGEN: PASS all 12 scenarios (return contract + extracted "
               "framebuffer state identical to kernel/mb2.c)\n");
        return 0;
    }
    printf("MB2-CODEGEN: FAIL %d scenario(s)\n", failures);
    return 1;
}
EOF

# 4. Compile: the codegen probe (freestanding) + the host harness, link host.
cc -ffreestanding -fno-builtin -nostdlib -std=c11 -c "$BUILD/mb2_codegen_probe.c" -o "$BUILD/mb2_codegen_probe.o"
cc -ffreestanding -fno-builtin -nostdlib -std=c11 -c "$HARNESS" -o "$BUILD/mb2_codegen_harness.o"
cc "$BUILD/mb2_codegen_probe.o" "$BUILD/mb2_codegen_harness.o" -o "$BUILD/mb2_codegen_run"

if "$BUILD/mb2_codegen_run"; then
  echo "PASS: Curlee mb2_parse walks the multiboot2 structure and extracts the framebuffer tag on the host (no QEMU needed)"
else
  echo "FAIL: mb2 tag-walk harness did not pass" >&2
  exit 1
fi
